#pragma once

#define FFKEYLOCK_VERSION_MAJOR 0
#define FFKEYLOCK_VERSION_MINOR 4
#define FFKEYLOCK_VERSION_PATCH 1
#define FFKEYLOCK_VERSION_TEXT "0.4.1"
#define FFKEYLOCK_VERSION_TEXT_W L"0.4.1"
#define FFKEYLOCK_VERSION_TEXT_RC "0.4.1\0"
