#pragma once

#define FFKEYLOCK_VERSION_MAJOR 0
#define FFKEYLOCK_VERSION_MINOR 5
#define FFKEYLOCK_VERSION_PATCH 0
#define FFKEYLOCK_VERSION_TEXT "0.5.0"
#define FFKEYLOCK_VERSION_TEXT_W L"0.5.0"
#define FFKEYLOCK_VERSION_TEXT_RC "0.5.0\0"
