#pragma once

#define FFKEYLOCK_VERSION_MAJOR 0
#define FFKEYLOCK_VERSION_MINOR 6
#define FFKEYLOCK_VERSION_PATCH 0
#define FFKEYLOCK_VERSION_TEXT "0.6.0"
#define FFKEYLOCK_VERSION_TEXT_W L"0.6.0"
#define FFKEYLOCK_VERSION_TEXT_RC "0.6.0\0"
